// lib/firebase_options.dart
// File generated by FlutterFire CLI. (แก้ให้รองรับ Web แล้ว)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // ✅ เดิมมัน throw; ตอนนี้ให้คืนค่า config ของ web
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⬇️ ใส่ค่าจริงของ Web จาก Firebase Console ที่นี่
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaDl9-kmdXn2JYF06Vt2APUSScImmPmg',
    authDomain: 'appstyle-picked.firebaseapp.com',        // เช่น appstyle-picked.firebaseapp.com
    projectId: 'appstyle-picked',                          // เช่น appstyle-picked
    storageBucket: 'appstyle-picked.firebasestorage.app',          // เช่น appstyle-picked.appspot.com
    messagingSenderId: '433207957549',
    appId: '1:433207957549:web:79b35b5f4c18737e6780a4',
    measurementId: 'G-CFQNH7H9QG',                        // ถ้ามีก็ใส่ ไม่มีก็ตัดบรรทัดนี้ทิ้งได้
  );

  // ⬇️ ของ Android (ของคุณเดิม)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnE7_CAC5vxMw0uPYfjEB2uEHSVVh4znQ',
    appId: '1:433207957549:android:c03b6d63f4b65cff6780a4',
    messagingSenderId: '433207957549',
    projectId: 'appstyle-picked',
    // ทั้ง 'appspot.com' และ 'firebasestorage.app' ใช้ได้ ขึ้นกับโปรเจกต์ของคุณ
    storageBucket: 'appstyle-picked.firebasestorage.app',
  );
}
